// Готовые темы оформления. У каждой светлый и тёмный вариант; цвета — из официальных палитр,
// местами затемнены или осветлены до читаемого контраста (проверяется в presets.test.ts)
import type {ThemePalette, ThemePreset} from './palette';

// Общие для светлых и тёмных вариантов полупрозрачные цвета
// Рамки заметные, как в настройках Edge и Оперы: панели и поля читаются как отдельные элементы
const LIGHT_EFFECTS = {
  cell: 'rgb(255 255 255 / 0.6)',
  border: 'rgb(0 0 0 / 0.14)',
  shadow: 'rgb(0 0 0 / 0.1)',
  shadowRaised: 'rgb(0 0 0 / 0.16)',
} satisfies Partial<ThemePalette>;

const DARK_EFFECTS = {
  cell: 'rgb(255 255 255 / 0.08)',
  border: 'rgb(255 255 255 / 0.16)',
  shadow: 'rgb(0 0 0 / 0.4)',
  shadowRaised: 'rgb(0 0 0 / 0.5)',
} satisfies Partial<ThemePalette>;

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'standard',
    name: 'Стандартная',
    // По образцу светлой и тёмной темы Edge: фон, панели и поля — три отчётливых тона,
    // основной текст почти чёрный или почти белый, второстепенный — не блёклый
    light: {
      ...LIGHT_EFFECTS,
      pageFrom: '#f3f4f6',
      pageTo: '#e6e9ed',
      surface: '#ffffff',
      surfaceMuted: '#f5f6f8',
      surfaceHover: '#eceef2',
      text: '#1a1c1f',
      textMuted: '#4b535d',
      accent: '#0066cc',
      accentHover: '#0052a3',
      accentText: '#ffffff',
      danger: '#cf222e',
      dangerText: '#ffffff',
      tile: '#ffffff',
      folder: '#e3eefc',
      plate: '#ffffff',
    },
    dark: {
      ...DARK_EFFECTS,
      pageFrom: '#20232b',
      pageTo: '#17191f',
      surface: '#2c3039',
      surfaceMuted: '#262a32',
      surfaceHover: '#363b46',
      text: '#f0f2f5',
      textMuted: '#b4bbc5',
      accent: '#5aa7ff',
      accentHover: '#80bbff',
      accentText: '#0e1014',
      danger: '#ff6a63',
      dangerText: '#0e1014',
      tile: '#2c3039',
      folder: '#27354a',
      plate: '#eceef1',
    },
  },
  {
    id: 'chrome',
    name: 'Chrome',
    light: {
      ...LIGHT_EFFECTS,
      pageFrom: '#ffffff',
      pageTo: '#f8fafd',
      surface: '#ffffff',
      surfaceMuted: '#f1f3f4',
      surfaceHover: '#e8eaed',
      text: '#202124',
      textMuted: '#5f6368',
      accent: '#1a73e8',
      accentHover: '#1765cc',
      accentText: '#ffffff',
      danger: '#d93025',
      dangerText: '#ffffff',
      tile: '#f1f3f4',
      folder: '#e8f0fe',
      plate: '#ffffff',
      border: 'rgb(60 64 67 / 0.12)',
      shadow: 'rgb(60 64 67 / 0.15)',
      shadowRaised: 'rgb(60 64 67 / 0.25)',
    },
    dark: {
      ...DARK_EFFECTS,
      pageFrom: '#202124',
      pageTo: '#1b1c1f',
      surface: '#292a2d',
      surfaceMuted: '#35363a',
      surfaceHover: '#3c4043',
      text: '#e8eaed',
      textMuted: '#9aa0a6',
      accent: '#8ab4f8',
      accentHover: '#aecbfa',
      accentText: '#202124',
      danger: '#f28b82',
      dangerText: '#202124',
      tile: '#35363a',
      folder: '#2b3649',
      plate: '#e8eaed',
    },
  },
  {
    id: 'edge',
    name: 'Edge',
    light: {
      ...LIGHT_EFFECTS,
      pageFrom: '#f7f7f7',
      pageTo: '#ebebeb',
      surface: '#ffffff',
      surfaceMuted: '#f5f5f5',
      surfaceHover: '#f0f0f0',
      text: '#242424',
      textMuted: '#616161',
      accent: '#0f6cbd',
      accentHover: '#115ea3',
      accentText: '#ffffff',
      danger: '#c50f1f',
      dangerText: '#ffffff',
      tile: '#ffffff',
      folder: '#ebf3fc',
      plate: '#ffffff',
    },
    dark: {
      ...DARK_EFFECTS,
      pageFrom: '#1f1f1f',
      pageTo: '#141414',
      surface: '#292929',
      surfaceMuted: '#2e2e2e',
      surfaceHover: '#383838',
      text: '#ffffff',
      textMuted: '#adadad',
      accent: '#479ef5',
      accentHover: '#62abf5',
      accentText: '#0a0a0a',
      danger: '#ee7b85',
      dangerText: '#0a0a0a',
      tile: '#292929',
      folder: '#0e2a4a',
      plate: '#f5f5f5',
    },
  },
  {
    id: 'opera',
    name: 'Opera',
    light: {
      ...LIGHT_EFFECTS,
      pageFrom: '#f1f2f6',
      pageTo: '#e4e6ee',
      surface: '#ffffff',
      surfaceMuted: '#f3f4f8',
      surfaceHover: '#eceef4',
      text: '#1a1b22',
      textMuted: '#5c5f6e',
      accent: '#d4001f',
      accentHover: '#b0001a',
      accentText: '#ffffff',
      danger: '#b3261e',
      dangerText: '#ffffff',
      tile: '#ffffff',
      folder: '#fbdce1',
      plate: '#ffffff',
    },
    dark: {
      ...DARK_EFFECTS,
      pageFrom: '#1c1d24',
      pageTo: '#121318',
      surface: '#26272f',
      surfaceMuted: '#2c2d36',
      surfaceHover: '#33343e',
      text: '#f1f1f4',
      textMuted: '#a2a4b3',
      accent: '#ff5566',
      accentHover: '#ff7885',
      accentText: '#16171c',
      danger: '#ff8a80',
      dangerText: '#16171c',
      tile: '#2a2b33',
      folder: '#3a232b',
      plate: '#ececf1',
    },
  },
  {
    id: 'github',
    name: 'GitHub',
    light: {
      ...LIGHT_EFFECTS,
      pageFrom: '#ffffff',
      pageTo: '#f6f8fa',
      surface: '#ffffff',
      surfaceMuted: '#f6f8fa',
      surfaceHover: '#eaeef2',
      text: '#1f2328',
      textMuted: '#59636e',
      accent: '#0969da',
      accentHover: '#0550ae',
      accentText: '#ffffff',
      danger: '#cf222e',
      dangerText: '#ffffff',
      tile: '#f6f8fa',
      folder: '#ddf4ff',
      plate: '#ffffff',
      border: 'rgb(31 35 40 / 0.15)',
    },
    dark: {
      ...DARK_EFFECTS,
      pageFrom: '#0d1117',
      pageTo: '#010409',
      surface: '#161b22',
      surfaceMuted: '#21262d',
      surfaceHover: '#262c36',
      text: '#f0f6fc',
      textMuted: '#9198a1',
      accent: '#4493f8',
      accentHover: '#58a6ff',
      accentText: '#0d1117',
      danger: '#f85149',
      dangerText: '#0d1117',
      tile: '#161b22',
      folder: '#12253f',
      plate: '#f0f6fc',
      border: 'rgb(240 246 252 / 0.12)',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    light: {
      ...LIGHT_EFFECTS,
      pageFrom: '#eceff4',
      pageTo: '#e5e9f0',
      surface: '#f8f9fb',
      surfaceMuted: '#eceff4',
      surfaceHover: '#e5e9f0',
      text: '#2e3440',
      textMuted: '#4c566a',
      accent: '#4b6b94',
      accentHover: '#3e5a7e',
      accentText: '#ffffff',
      danger: '#a5444e',
      dangerText: '#ffffff',
      tile: '#f8f9fb',
      folder: '#dde6f0',
      plate: '#ffffff',
    },
    dark: {
      ...DARK_EFFECTS,
      pageFrom: '#2e3440',
      pageTo: '#272c36',
      surface: '#3b4252',
      surfaceMuted: '#434c5e',
      surfaceHover: '#4c566a',
      text: '#eceff4',
      textMuted: '#c0c8d6',
      accent: '#88c0d0',
      accentHover: '#8fbcbb',
      accentText: '#2e3440',
      danger: '#f0a0a6',
      dangerText: '#2e3440',
      tile: '#3b4252',
      folder: '#394a5e',
      plate: '#eceff4',
    },
  },
  {
    id: 'catppuccin',
    name: 'Catppuccin',
    light: {
      ...LIGHT_EFFECTS,
      pageFrom: '#e6e9ef',
      pageTo: '#dce0e8',
      surface: '#eff1f5',
      surfaceMuted: '#e6e9ef',
      surfaceHover: '#dce0e8',
      text: '#4c4f69',
      textMuted: '#5c5f77',
      accent: '#8839ef',
      accentHover: '#7424e0',
      accentText: '#ffffff',
      danger: '#d20f39',
      dangerText: '#ffffff',
      tile: '#f7f8fa',
      folder: '#e6ddfb',
      plate: '#ffffff',
    },
    dark: {
      ...DARK_EFFECTS,
      pageFrom: '#1e1e2e',
      pageTo: '#181825',
      surface: '#313244',
      surfaceMuted: '#3a3c50',
      surfaceHover: '#45475a',
      text: '#cdd6f4',
      textMuted: '#a6adc8',
      accent: '#cba6f7',
      accentHover: '#d8bcfa',
      accentText: '#1e1e2e',
      danger: '#f38ba8',
      dangerText: '#1e1e2e',
      tile: '#313244',
      folder: '#3b3354',
      plate: '#eff1f5',
    },
  },
  {
    id: 'solarized',
    name: 'Solarized',
    light: {
      ...LIGHT_EFFECTS,
      pageFrom: '#fdf6e3',
      pageTo: '#eee8d5',
      surface: '#fdf6e3',
      surfaceMuted: '#f5eedb',
      surfaceHover: '#eee8d5',
      text: '#073642',
      textMuted: '#586e75',
      accent: '#1d6fa5',
      accentHover: '#175a87',
      accentText: '#fdf6e3',
      danger: '#b8261f',
      dangerText: '#fdf6e3',
      tile: '#fffbef',
      folder: '#dcebe6',
      plate: '#fffdf6',
    },
    dark: {
      ...DARK_EFFECTS,
      pageFrom: '#002b36',
      pageTo: '#00212b',
      surface: '#073642',
      surfaceMuted: '#0b404e',
      surfaceHover: '#104a59',
      text: '#eee8d5',
      textMuted: '#a7b4b4',
      accent: '#5eaee8',
      accentHover: '#7cbdec',
      accentText: '#002b36',
      danger: '#f68884',
      dangerText: '#002b36',
      tile: '#073642',
      folder: '#0a4a4a',
      plate: '#fdf6e3',
    },
  },
  {
    id: 'gruvbox',
    name: 'Gruvbox',
    light: {
      ...LIGHT_EFFECTS,
      pageFrom: '#fbf1c7',
      pageTo: '#f2e5bc',
      surface: '#f9f5d7',
      surfaceMuted: '#f2e5bc',
      surfaceHover: '#ebdbb2',
      text: '#3c3836',
      textMuted: '#665c54',
      accent: '#076678',
      accentHover: '#055565',
      accentText: '#fbf1c7',
      danger: '#9d0006',
      dangerText: '#fbf1c7',
      tile: '#f9f5d7',
      folder: '#e3e4c3',
      plate: '#fdf8e1',
    },
    dark: {
      ...DARK_EFFECTS,
      pageFrom: '#282828',
      pageTo: '#1d2021',
      surface: '#32302f',
      surfaceMuted: '#3c3836',
      surfaceHover: '#504945',
      text: '#ebdbb2',
      textMuted: '#bdae93',
      accent: '#fabd2f',
      accentHover: '#fcd06a',
      accentText: '#282828',
      danger: '#fd8672',
      dangerText: '#282828',
      tile: '#32302f',
      folder: '#3e3b2c',
      plate: '#fbf1c7',
    },
  },
  {
    id: 'rose-pine',
    name: 'Rosé Pine',
    light: {
      ...LIGHT_EFFECTS,
      pageFrom: '#faf4ed',
      pageTo: '#f2e9e1',
      surface: '#fffaf3',
      surfaceMuted: '#f2e9e1',
      surfaceHover: '#ebe2da',
      text: '#575279',
      textMuted: '#6a6590',
      accent: '#286983',
      accentHover: '#1f566b',
      accentText: '#fffaf3',
      danger: '#a3506a',
      dangerText: '#fffaf3',
      tile: '#fffaf3',
      folder: '#f6e3dd',
      plate: '#ffffff',
    },
    dark: {
      ...DARK_EFFECTS,
      pageFrom: '#232136',
      pageTo: '#1f1d30',
      surface: '#2a273f',
      surfaceMuted: '#393552',
      surfaceHover: '#44415a',
      text: '#e0def4',
      textMuted: '#aeaacb',
      accent: '#c4a7e7',
      accentHover: '#d3bdee',
      accentText: '#232136',
      danger: '#eb6f92',
      dangerText: '#232136',
      tile: '#2a273f',
      folder: '#393552',
      plate: '#faf4ed',
    },
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    light: {
      ...LIGHT_EFFECTS,
      pageFrom: '#e6e7ed',
      pageTo: '#d5d6db',
      surface: '#f2f3f7',
      surfaceMuted: '#e6e7ed',
      surfaceHover: '#dcdde3',
      text: '#343b58',
      textMuted: '#565a6e',
      accent: '#34548a',
      accentHover: '#2a4570',
      accentText: '#ffffff',
      danger: '#8c4351',
      dangerText: '#ffffff',
      tile: '#f2f3f7',
      folder: '#dde3f2',
      plate: '#ffffff',
    },
    dark: {
      ...DARK_EFFECTS,
      pageFrom: '#1a1b26',
      pageTo: '#16161e',
      surface: '#24283b',
      surfaceMuted: '#292e42',
      surfaceHover: '#2f3549',
      text: '#c0caf5',
      textMuted: '#a9b1d6',
      accent: '#7aa2f7',
      accentHover: '#96b6f9',
      accentText: '#1a1b26',
      danger: '#f7768e',
      dangerText: '#1a1b26',
      tile: '#24283b',
      folder: '#2a2f4a',
      plate: '#e1e2e7',
    },
  },
];

export const THEME_PRESET_IDS = [...THEME_PRESETS.map((preset) => preset.id), 'custom'] as const;

export const DEFAULT_THEME_PRESET = 'standard';
